# Generated by Django 4.2 on 2023-04-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='WhiteListTokenDevice',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dasdsada', to='token_blacklist.outstandingtoken'),
        ),
        migrations.CreateModel(
            name='WhiteListTokenDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist', to='token_blacklist.outstandingtoken')),
            ],
        ),
    ]
